<?php

namespace AppBundle\Repository;

/**
 * StudentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentsRepository extends \Doctrine\ORM\EntityRepository
{
}
