<?php

namespace AppBundle\Repository;

/**
 * UniversidadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniversidadeRepository extends \Doctrine\ORM\EntityRepository
{
}
